### ISSUE TITLE
Dynamic less library in packed mode

### ISSUE THREAD

**Issue by ludoo0d0a** [c9/core#57]
My workspace panel doesn't appear anymore.
install-sdk and reset preferences don't change anything.

The console displays : 
```
Can't add dynamic less library in packed mode!
```

LESS code trying to added starts with 
```css
.panelsbutton{
                padding : 10px 10px 6px 10px;
                display : inline-block;
                white-space: nowrap;
                cursor : default;
                
                margin-left : -1px;
                margin-right : 2px;
                font-family: Helvetica, Arial;
                font-size: @general-font-size;
                color : @panel-button-color;
                text-shadow: @panel-button-text-shadow;

                .transform(rotate(180deg));
                
                height : 18px;
            }
```

I don't set packed option but this var is true anyway.
I saw that it is defined by style.css length
So after empty plugins/c9.ide.ui/style.css, left panel appears.
